name: ML Testing Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.0.1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.15

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy joblib scikit-learn pytest gcsfs "dvc[gs]" cml

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Pull DVC artifacts
        run: dvc pull

      - name: Run pytest
        run: pytest test_pipeline.py --maxfail=1 --disable-warnings -v --junitxml=report.xml
        
      - name: Post PR comment via CML
        run: cml send-comment report.xml
